### ISSUE TITLE
Feature Request: Display added mining speed separately

### ISSUE THREAD

**Issue by alterNERDtive** [Hannah-GBS/VH-Jewel-Calc#10]
Currently your jewels’ mining speed gets rolled into the tool’s total. Resources like the community guide spreadsheet list mining speed requirements _excluding_ the tool’s 9 innate mining speed. So instead of e.g.

```
Mining Speed: 19
```

it would be nice to have something like

```
Mining Speed: 19 (+10)
```

or

```
Total Mining Speed: 19
Added Mining Speed: +10
```

**Comment by Hannah-GBS** [comment]
The first suggestion, `19 (+10)` would be by far the easiest to implement. I will look into that when I get a chance.

**Comment by DZK312** [comment]
suggesstion for two *possible* alternatives to this. you could also maybe move the innates (9 mining speed and 4096 dura) to the prefixes box or make a separate small box for the innates that dont combine with the rest.

**Comment by Hannah-GBS** [comment]
It feels a bit weird moving them to prefixes, especially as the number of potential prefixes is already higher than suffixes. If you can think of a good place to put the intrinsic stats (the first level of Hammering would also fit) separately then I would definitely consider that.

**Comment by Hannah-GBS** [comment]
I suppose I could omit the 9 mining speed and 4096 durability altogether, since it's constant on every tool, and just have a minimise-able note about that on the page. Not sure how I'd go about dealing with tools saved before that change though, as the intrinsics are not separate internally either.

**Comment by DZK312** [comment]
Here's an idea for the innate modifier placement
![image](https://user-images.githubusercontent.com/91441656/224946597-cb5fa9c4-7428-4018-9539-72c647d8c0b3.png)
![image](https://user-images.githubusercontent.com/91441656/224946620-b8e01573-c007-43ee-a169-e1b752016b07.png)
I prefer them being at the top personally. Also if mining speed and dura are added on, they should be specified as "+[#]" so like "+20.3" or "+789". I feel like hammering should stay out of innates tho.

**Comment by Hannah-GBS** [comment]
That's not bad at all. Yeah I'd use the +XX format for those values.

As for hammer size, it *does* follow the same format in game though, where it has 1 innately, and any extra are "+X" in a suffix. Feels weird to leave it out.

**Comment by alterNERDtive** [comment]
Top :+1:
