### ISSUE TITLE
Slam the Hammer

### ISSUE THREAD

**Issue by DZK312** [Hannah-GBS/VH-Jewel-Calc#11]
The existence of "Hammering" and "Hammer Size" feels redundant, especially since they both show up in drop downs.
![image](https://user-images.githubusercontent.com/91441656/224948028-cbc9b0c4-2048-4ab5-b397-9800cf01a50f.png)

The one that doesnt show up on jewels and increase should just be rid of entirely imo. The "Hammer Size 1" *should* be self explanatory enough. Just gets confusing otherwise.

**Comment by Hannah-GBS** [comment]
While I'm not interested in removing legitimate filtering options on tools even if redundant, I have pushed a fix to remove Hammering and Reaping on the jewel sort/filter lists.
