### ISSUE TITLE
Sort/Filter by Attribute

### ISSUE THREAD

**Issue by DZK312** [Hannah-GBS/VH-Jewel-Calc#2]
it would be nice if there was a drop down menu to sort or filter by a certain attribute. So like if I wanted to see all my mining speed jewels to build a tool, I coul do so, since by default they are exclusively sorted order of input.

**Comment by Hannah-GBS** [comment]
This is definitely a planned feature! I'm torn between another dropdown for filtering or a search bar. It's probably quicker to type in the first few letters of most modifiers, but the rest of the page does use dropdowns so maybe being consistent there would be better? Not sure.

**Comment by DZK312** [comment]
well why not opt for a fuson of the two, a search bar with a drop down arrow at the end, and it can autofill to match your search input to existing options?
