### ISSUE TITLE
Copiously display bugged sometimes

### ISSUE THREAD

**Issue by DZK312** [Hannah-GBS/VH-Jewel-Calc#3]
![image](https://user-images.githubusercontent.com/91441656/220498473-dcb807d2-555f-442e-86b5-a51c9f23ce49.png)
![image](https://user-images.githubusercontent.com/91441656/220498549-a5b8305c-2274-4188-b312-9df454689b6b.png)

Idk what causes it, but sometimes copiously percent tuns into a number with a lot of decimal 0s and runs out of bounds.
it doesnt always happen, I have 3 copiously jewels atm and this is the only bugged one. Also the numbers itself are wrong (idr what I put it as and can't check in game atm)

**Comment by Hannah-GBS** [comment]
I'm not entirely sure what would cause this, and am unable to recreate it, but I'll add some extra safeguarding around decimal places in the next site update and hopefully that'll sort it.
