### ISSUE TITLE
Cannot remove jewels depending on size

### ISSUE THREAD

**Issue by ZeterTheDuck** [Hannah-GBS/VH-Jewel-Calc#4]
When applying jewels to a tool, if the size of the jewel you want to remove is bigger than the tool's size, you can't remove it. The only way to undo this is to return the tool and jewels back to their places, then do everything over again. Or you can remove smaller jewels until you can remove the one that you want.

**Comment by Hannah-GBS** [comment]
You might need to do a hard refresh (Ctrl + F5) to see the fix on your end.
