### ISSUE TITLE
Sort by Value

### ISSUE THREAD

**Issue by DZK312** [Hannah-GBS/VH-Jewel-Calc#5]
Another very convenient sort method would be to sort the attributes by their true value (aka the ratio of value to size) so that your best bang-for-your-buck jewels are at the top, and the ones with the worst rates are at the bottom. This would be particularly useful with the attribute filter. In the case of jewels with multiple traits, you could do a calc for each attribute (like if i had 0.6 item rarity and 2.4 mining speed with size 37, it would sort by the mining speed **if** a filter _isnt_ selected.)

**Comment by Hannah-GBS** [comment]
Yeah this is something I've got working in dev already. For simplicity I've got it so if you select sort by Attribute Efficiency another dropdown appears to select 1 attribute to sort by. Jewels with that attribute will be sorted to the top and in order of efficiency.
