### ISSUE TITLE
New Jewels Adopt "Choose Attribute" Attribute

### ISSUE THREAD

**Issue by DZK312** [Hannah-GBS/VH-Jewel-Calc#7]
Since the update, newly made jewels have the "Choose Attribute" attribute listed under them and they color swap with a blank color.

![image](https://user-images.githubusercontent.com/91441656/222660795-fb16f2ba-036e-4400-991e-f46c3c9c9f6d.png)

**Comment by Hannah-GBS** [comment]
Well that's frustrating. Looking into it.
